### ISSUE TITLE
Kind request to hide package from Atmosphere

### ISSUE THREAD

**Issue by dandv** [mangasocial/meteor-accounts-ui-bootstrap-3#103]
Hey @yasinuslu,

While looking for accounts-ui packages for Bootstrap 3 on Atmosphere I found [yours](https://atmospherejs.com/yasinuslu/accounts-ui-bootstrap-3). It looks like you haven't had time to maintain it, which is perfectly ok.

In the meantime though, much more actively maintained packages have appeared, such as @ianmartorell's https://atmospherejs.com/ian/accounts-ui-bootstrap-3.

To keep Atmosphere clean, we kindly ask you to hide the old package. No worries, it will still be installable by apps and dependent packages; it will just be hidden from Atmosphere searches:

    meteor admin set-unmigrated yasinuslu:accounts-ui-bootstrap-3

Thanks,
Dan
Atmosphere curator

**Comment by yasinuslu** [comment]
I didn't know we could flag package as unmigrated. I'll do it immediately.

**Comment by dandv** [comment]
Thanks, confirmed hidden!
