### ISSUE TITLE
Feature request: password confirmation field

### ISSUE THREAD

**Issue by steph643** [mangasocial/meteor-accounts-ui-bootstrap-3#104]
It seems there is no password confirmation field when creating an account or changing the password in the dropdown (although there is one in the reset password modal). Don't you think it is standard practice to have one?

**Comment by yasinuslu** [comment]
https://github.com/mangasocial/meteor-accounts-ui-bootstrap-3/blob/master/README.md

This repo is not maintained, please open you issue at https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/
